Add Linters file
DanielOTagua/Hello-Microverse-1 pull request #1
Opened 2023-06-07 18:16 UTC by DanielOTagua

In this PR, I was able to:
create index.html
create style.css
create .gitignore file
and set up Linters

2023-06-07 19:52 UTC, Ofarouq310 requested changes
Hi @DanielOTagua, ✋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🥈 

![giphy](https://github.com/DanielOTagua/Hello-Microverse-1/assets/102612396/b57a0a67-e0aa-4c57-a4c2-a5d7f10a2fde)

 ## Highlights
✅ Followed GitHub workflow.
✅ Descriptive PR title & summary.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 19:52 UTC, Ofarouq310 commented on .github/linters.yml
- [ ] As requested by the previous reviewer, the linters setup is not working properly, kindly fix the folder structure because it has to be `.github/workflows/linters.yml`, you are missing the `workflows` folder.

---

- _Kindly refer to this [lesson](https://github.com/Ofarouq310/linters-config/tree/master/html-css) to cover everything._

2023-06-07 19:52 UTC, Ofarouq310 commented on README.md
[OPTIONAL]
- [ ] Kindly remove any part like this one, this is just for your guidance, leaving it may seem inappropriate and unprofessional.

2023-06-08 00:40 UTC, DanielOTagua commented
Hello sorry but i can´t fix al the time this error is coming out
To https://github.com/DanielOTagua/Hello-Microverse-1.git
 ! [remote rejected] Linters -> Linters (refusing to allow a Personal
Access Token to create or update workflow `.github/workflows/linters.yml`
without `workflow` scope)
error: failed to push some refs to '
https://github.com/DanielOTagua/Hello-Microverse-1.git'

how I can get help ???


El mié, 7 jun 2023 a la(s) 16:52, Omar Farouq ***@***.***)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Hi @DanielOTagua <https://github.com/DanielOTagua>, ✋
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet. 🥈
>
> [image: giphy]
> <https://user-images.githubusercontent.com/102612396/244180110-b57a0a67-e0aa-4c57-a4c2-a5d7f10a2fde.gif>
> Highlights
>
> ✅ Followed GitHub workflow.
> ✅ Descriptive PR title & summary.
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> On .github/linters.yml
> <https://github.com/DanielOTagua/Hello-Microverse-1/pull/1#discussion_r1222083955>
> :
>
>    - As requested by the previous reviewer, the linters setup is not
>    working properly, kindly fix the folder structure because it has to be
>    .github/workflows/linters.yml, you are missing the workflows folder.
>
> ------------------------------
>
>    - *Kindly refer to this lesson
>    <https://github.com/Ofarouq310/linters-config/tree/master/html-css> to
>    cover everything.*
>
> ------------------------------
>
> In README.md
> <https://github.com/DanielOTagua/Hello-Microverse-1/pull/1#discussion_r1222085135>
> :
>
> >
>  > Describe your project in 1 or 2 sentences.
>
>
> [OPTIONAL]
>
>    - Kindly remove any part like this one, this is just for your
>    guidance, leaving it may seem inappropriate and unprofessional.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DanielOTagua/Hello-Microverse-1/pull/1#pullrequestreview-1468441255>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUV4AWI6ORGLKOM7UYFWZGDXKDLYJANCNFSM6AAAAAAY6HESRA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-08 02:11 UTC, stanleySimeon approved these changes
# Hi @DanielOTagua 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 02:24 UTC, merged